version: '3'


# Konfiguracja serwera
services:
  web:
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
    ports:
      - "8080:80" # Map port 80 in the container to port 8080 on the host
    volumes:
      - .:/app/   # Mount the current directory to /app in the container
    links:
      - php
    networks:
      - pg-network
  
  # Konfiguracja bazy danych
  db:
    build:
      context: .
      dockerfile: docker/db/Dockerfile
    ports:
      - "5432:5432"  # Po lewo lokalny port, po prawo port w kontenerze, z php łączymy sie do kontenera, pgadmin też (ale np navicat łączyłby się do localhost:5432)
    networks:
      - pg-network
  
  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    volumes:
      - .:/app
    networks:
      - pg-network
  
  pgadmin-wdpai:
    image: dpage/pgadmin4:latest
    container_name: pg-admin2
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    networks:
      - pg-network
  
networks:
  pg-network:

volumes:
  pg-data: